# From the NumPy Documentation 

https://numpy.org/doc/stable/user/quickstart.html

In [4]:
import numpy as np

In [8]:
list(range(2, 12,3))

[2, 5, 8, 11]

In [10]:
x = np.arange(1.6, 40.3, 2)

In [11]:
x

array([ 1.6,  3.6,  5.6,  7.6,  9.6, 11.6, 13.6, 15.6, 17.6, 19.6, 21.6,
       23.6, 25.6, 27.6, 29.6, 31.6, 33.6, 35.6, 37.6, 39.6])

In [12]:
x.dtype

dtype('float64')

In [13]:
x.shape

(20,)

In [5]:
a = np.arange(15).reshape(3, 5)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

In [16]:
x.reshape(-1, 1)

array([[ 1.6],
       [ 3.6],
       [ 5.6],
       [ 7.6],
       [ 9.6],
       [11.6],
       [13.6],
       [15.6],
       [17.6],
       [19.6],
       [21.6],
       [23.6],
       [25.6],
       [27.6],
       [29.6],
       [31.6],
       [33.6],
       [35.6],
       [37.6],
       [39.6]])

In [19]:
x = np.arange(0.1, 20.0, 0.1)
x

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15

In [20]:
y = x**2
y

array([1.0000e-02, 4.0000e-02, 9.0000e-02, 1.6000e-01, 2.5000e-01,
       3.6000e-01, 4.9000e-01, 6.4000e-01, 8.1000e-01, 1.0000e+00,
       1.2100e+00, 1.4400e+00, 1.6900e+00, 1.9600e+00, 2.2500e+00,
       2.5600e+00, 2.8900e+00, 3.2400e+00, 3.6100e+00, 4.0000e+00,
       4.4100e+00, 4.8400e+00, 5.2900e+00, 5.7600e+00, 6.2500e+00,
       6.7600e+00, 7.2900e+00, 7.8400e+00, 8.4100e+00, 9.0000e+00,
       9.6100e+00, 1.0240e+01, 1.0890e+01, 1.1560e+01, 1.2250e+01,
       1.2960e+01, 1.3690e+01, 1.4440e+01, 1.5210e+01, 1.6000e+01,
       1.6810e+01, 1.7640e+01, 1.8490e+01, 1.9360e+01, 2.0250e+01,
       2.1160e+01, 2.2090e+01, 2.3040e+01, 2.4010e+01, 2.5000e+01,
       2.6010e+01, 2.7040e+01, 2.8090e+01, 2.9160e+01, 3.0250e+01,
       3.1360e+01, 3.2490e+01, 3.3640e+01, 3.4810e+01, 3.6000e+01,
       3.7210e+01, 3.8440e+01, 3.9690e+01, 4.0960e+01, 4.2250e+01,
       4.3560e+01, 4.4890e+01, 4.6240e+01, 4.7610e+01, 4.9000e+01,
       5.0410e+01, 5.1840e+01, 5.3290e+01, 5.4760e+01, 5.6250e

In [22]:
np.linspace(0.0, 10.0, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
I = np.eye(3)

In [26]:
I.dtype

dtype('float64')

In [27]:
I.astype('int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [30]:
I[2]

array([0., 0., 1.])

# End Cell